import { defineField, defineType } from "sanity";

export const serviceType = defineType({
  name: "service",
  title: "Dịch vụ",
  type: "document",
  groups: [
    { name: "basic", title: "Thông tin", default: true },
    { name: "display", title: "Hiển thị" },
    { name: "content", title: "Nội dung" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Tên dịch vụ",
      type: "string",
      group: "basic",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "shortTitle",
      title: "Tên ngắn",
      type: "string",
      group: "basic",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Đường dẫn",
      type: "slug",
      group: "basic",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "summary",
      title: "Mô tả ngắn",
      type: "text",
      group: "basic",
      rows: 3,
      validation: (rule) => rule.required().max(240),
    }),
    defineField({
      name: "group",
      title: "Nhóm dịch vụ",
      type: "string",
      group: "display",
      initialValue: "kham-chua-benh",
      options: {
        list: [
          { title: "Pet Shop", value: "pet-shop" },
          { title: "Pet Hotel", value: "pet-hotel" },
          { title: "Khám chữa bệnh", value: "kham-chua-benh" },
          { title: "Spa / Grooming", value: "spa-grooming" },
          { title: "Phẫu thuật", value: "phau-thuat" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "cardImage",
      title: "Ảnh thẻ dịch vụ",
      type: "image",
      group: "display",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Mô tả ảnh",
          type: "string",
          validation: (rule) => rule.required(),
        }),
      ],
    }),
    defineField({
      name: "featuredOnHome",
      title: "Hiển thị trong Top dịch vụ trang chủ",
      type: "boolean",
      group: "display",
      initialValue: false,
    }),
    defineField({
      name: "homeOrder",
      title: "Thứ tự trên trang chủ",
      type: "number",
      group: "display",
      initialValue: 10,
    }),
    defineField({
      name: "description",
      title: "Nội dung giới thiệu",
      type: "text",
      group: "content",
      rows: 6,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "points",
      title: "Các bước chính",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      validation: (rule) => rule.required().min(2).max(5),
    }),
    defineField({
      name: "accent",
      title: "Màu nhấn",
      type: "string",
      group: "display",
      initialValue: "blue",
      options: {
        list: [
          { title: "Xanh y tế", value: "blue" },
          { title: "Đỏ chăm sóc", value: "red" },
          { title: "Xanh navy", value: "navy" },
          { title: "Xanh băng", value: "ice" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "order",
      title: "Thứ tự",
      type: "number",
      group: "display",
      initialValue: 10,
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "summary" },
  },
});
