import { defineField, defineType } from "sanity";

import { fallbackSiteSettings } from "@/lib/site-config";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Cài đặt chung",
  type: "document",
  groups: [
    { name: "brand", title: "Thương hiệu", default: true },
    { name: "contact", title: "Liên hệ" },
    { name: "social", title: "Mạng xã hội" },
    { name: "seo", title: "SEO" },
    { name: "footer", title: "Footer" },
  ],
  initialValue: {
    name: fallbackSiteSettings.name,
    tagline: fallbackSiteSettings.tagline,
    title: fallbackSiteSettings.title,
    description: fallbackSiteSettings.description,
    footerDescription: fallbackSiteSettings.footerDescription,
    footerDisclaimer: fallbackSiteSettings.footerDisclaimer,
    phone: fallbackSiteSettings.phone,
    email: fallbackSiteSettings.email,
    address: fallbackSiteSettings.address,
    openingHours: fallbackSiteSettings.openingHours,
    googleMapsUrl: fallbackSiteSettings.googleMapsUrl,
    googleMapsEmbedUrl: fallbackSiteSettings.googleMapsEmbedUrl,
    facebookUrl: fallbackSiteSettings.facebookUrl,
    instagramUrl: fallbackSiteSettings.instagramUrl,
    zaloUrl: fallbackSiteSettings.zaloUrl,
  },
  fields: [
    defineField({
      name: "name",
      title: "Tên thương hiệu",
      type: "string",
      group: "brand",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tagline",
      title: "Dòng chữ dưới logo",
      type: "string",
      group: "brand",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "logo",
      title: "Logo",
      type: "image",
      group: "brand",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Mô tả ảnh",
          type: "string",
          validation: (rule) => rule.required(),
        }),
      ],
    }),
    defineField({
      name: "phone",
      title: "Số điện thoại chính",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "email",
      title: "Email",
      type: "email",
      group: "contact",
    }),
    defineField({
      name: "address",
      title: "Địa chỉ chính",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "openingHours",
      title: "Giờ hoạt động",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "googleMapsUrl",
      title: "Link Google Maps",
      type: "url",
      group: "contact",
    }),
    defineField({
      name: "googleMapsEmbedUrl",
      title: "Link nhúng Google Maps",
      type: "url",
      group: "contact",
    }),
    defineField({
      name: "facebookUrl",
      title: "Facebook",
      type: "url",
      group: "social",
    }),
    defineField({
      name: "instagramUrl",
      title: "Instagram",
      type: "url",
      group: "social",
    }),
    defineField({
      name: "zaloUrl",
      title: "Zalo",
      type: "url",
      group: "social",
    }),
    defineField({
      name: "title",
      title: "Tiêu đề mặc định trên Google",
      type: "string",
      group: "seo",
      validation: (rule) => rule.required().max(70),
    }),
    defineField({
      name: "description",
      title: "Mô tả mặc định trên Google",
      type: "text",
      rows: 3,
      group: "seo",
      validation: (rule) => rule.required().max(180),
    }),
    defineField({
      name: "footerDescription",
      title: "Mô tả ngắn ở footer",
      type: "text",
      rows: 3,
      group: "footer",
    }),
    defineField({
      name: "footerDisclaimer",
      title: "Lưu ý cuối trang",
      type: "string",
      group: "footer",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Cài đặt chung toàn website" }),
  },
});
